import type { Article } from '@/apis/groups';

export const DUMMY_ARTICLES_DATA: Article[] = [
  {
    articleId: 1,
    userId: 1,
    images: ['/images/dummy_avatar.png', '/images/dummy_image.png'],
    notice: true,
    userImageUrl: '/images/dummy_avatar.png',
    name: 'Ahn Ki Hyeon',
    date: '2023-10-29T20:22:33Z',
    content:
      '안녕하세요! 모임에 가입해주셔서 감사드립니다.\n오늘 19:00에 있을 모임 참여 전 모임에 필요한 공지 및 전달사항 확인 부탁드리겠습니다.',
    commentCount: 0,
    isWriter: true,
    isWriterCaptain: true,
    isWriterCertifiedStudent: true,
    writerReliabilityLevel: 'HOOD',
  },
  {
    articleId: 2,
    userId: 2,
    images: [],
    notice: false,
    userImageUrl: '/images/dummy_avatar.png',
    name: 'Kim',
    date: '2023.09.01',
    content: '안녕하세요! 모임에 가입해주셔서 감사드립니다.',
    commentCount: 100,
    isWriter: false,
    isWriterCaptain: false,
    isWriterCertifiedStudent: false,
    writerReliabilityLevel: 'HOOD',
  },
  {
    articleId: 3,
    userId: 2,
    images: ['/images/dummy_image.png', '/images/dummy_image.png', '/images/dummy_image.png'],
    notice: false,
    userImageUrl: '/images/dummy_avatar.png',
    name: 'Kim',
    date: '2021.09.01',
    content:
      '안녕하세요! 모임에 가입해주셔서 감사드립니다.\n오늘 19:00에 있을 모임 참여 전 모임에 필요한 공지 및 전달사항 확인 부탁드리겠습니다.',
    commentCount: 0,
    isWriter: false,
    isWriterCaptain: false,
    isWriterCertifiedStudent: false,
    writerReliabilityLevel: 'HOOD',
  },
];
